# Generated by Django 4.1.1 on 2022-11-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharin', '0008_alter_publicacao_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
